"""Update displacement and force to Float

Revision ID: 60d5f8caef8b
Revises: dacec1a28ae7
Create Date: 2024-12-04 11:30:34.776262

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '60d5f8caef8b'
down_revision: Union[str, None] = 'dacec1a28ae7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('device_data', 'displacement',
               existing_type=sa.VARCHAR(),
               type_=sa.Float(),
               existing_nullable=False)
    op.alter_column('device_data', 'force',
               existing_type=sa.VARCHAR(),
               type_=sa.Float(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('device_data', 'force',
               existing_type=sa.Float(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.alter_column('device_data', 'displacement',
               existing_type=sa.Float(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    # ### end Alembic commands ###
