"""Initial migration

Revision ID: dacec1a28ae7
Revises: 
Create Date: 2024-12-04 11:05:31.998494

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dacec1a28ae7'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('client_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.String(), nullable=True),
    sa.Column('websocket_id', sa.String(), nullable=True),
    sa.Column('connected', sa.Boolean(), nullable=True),
    sa.Column('last_connected_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_client_sessions_client_id'), 'client_sessions', ['client_id'], unique=True)
    op.create_index(op.f('ix_client_sessions_id'), 'client_sessions', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('hashed_password', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('iot_devices',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('device_name', sa.String(), nullable=False),
    sa.Column('device_type', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('device_token', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('device_token')
    )
    op.create_index(op.f('ix_iot_devices_device_name'), 'iot_devices', ['device_name'], unique=False)
    op.create_index(op.f('ix_iot_devices_id'), 'iot_devices', ['id'], unique=False)
    op.create_table('device_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('displacement', sa.String(), nullable=False),
    sa.Column('force', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['iot_devices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_device_data_device_id'), 'device_data', ['device_id'], unique=False)
    op.create_index(op.f('ix_device_data_id'), 'device_data', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_device_data_id'), table_name='device_data')
    op.drop_index(op.f('ix_device_data_device_id'), table_name='device_data')
    op.drop_table('device_data')
    op.drop_index(op.f('ix_iot_devices_id'), table_name='iot_devices')
    op.drop_index(op.f('ix_iot_devices_device_name'), table_name='iot_devices')
    op.drop_table('iot_devices')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_client_sessions_id'), table_name='client_sessions')
    op.drop_index(op.f('ix_client_sessions_client_id'), table_name='client_sessions')
    op.drop_table('client_sessions')
    # ### end Alembic commands ###
